AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Function from Cloud Formation by Abdullah'

Resources:
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties:
        
        Code:
            ZipFile: >
                import json

                import urllib.parse

                import boto3

                print('Loading function')

                s3 = boto3.client('s3')

                def lambda_handler(event, context):
                    #print("Received event: " + json.dumps(event, indent=2))
                    # Get the object from the event and show its content type
                    bucket = event['Records'][0]['s3']['bucket']['name']
                    key = urllib.parse.unquote_plus(event['Records'][0]['s3']['object']['key'], encoding='utf-8')
                    try:
                        response = s3.get_object(Bucket=bucket, Key=key)
                        print("CONTENT TYPE: " + response['ContentType'])
                        return response['ContentType']
                    except Exception as e:
                        print(e)
                        print('Error getting object {} from bucket {}. Make sure they exist and your bucket is in the same region as this function.'.format(key, bucket))
                        raise e
              
        Description: Test with Cloud Formation
        FunctionName: TstLambdaFunction
        Handler: index.lambda_handler
        Role: arn:aws:iam::312711150750:role/example-s3-role
        Runtime: python3.9